name: Test, Build, and Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'  # Specify the Node.js version (adjust if necessary)

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run tests (optional step, can be skipped if not needed)
      - name: Run tests
        run: npm test -- --coverage

      # Build the app
      - name: Build the app
        run: npm run build

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        run: |
          npm install --save gh-pages
          npm run deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # GitHub automatically provides this token
